name: Run Tests

on:
  push:
    branches: [ develop, main, feature/* ]
  pull_request:
    branches: [ develop, main, feature/* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests_and_code_coverage:
    name: Run Tests and Code Coverage
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3.0'
      - name: Run Tests
        run: xcodebuild test -scheme SocialAuthentication -destination "OS=18.6,name=iPhone 16"
      - name: Upload Xcode Code Coverage Report to CodeCov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          xcode: true
